module HighwireShrimper
  module IRC
    module Commands
      class Ping
        attr_reader server1: ServerName
        attr_reader server2: ServerName?

        def initialize: (server1: server_identifier, server2: server_identifier?) -> void
      end
    end
  end
end
