module HighwireShrimper
  module IRC
    class Server
      attr_reader name: String
      attr_reader hostname: ServerName
      attr_reader port: Integer

      def initialize: (name: String, hostname: server_identifier, port: Integer, ssl: bool) -> void

      def ssl?: -> bool
    end
  end
end
